### ISSUE TITLE
pip install fails when setup.py is unable to find a library in DEFAULT_LIBRARIES

### ISSUE THREAD

**Issue by jasonwashburn** [eengl/grib2io#19]
When trying to pip install, install fails with the following error:

```python
Collecting grib2io
  Using cached grib2io-0.9.2.tar.gz (669 kB)
    ERROR: Command errored out with exit status 1:
     command: /workspace/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a9lbp5i8/grib2io/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a9lbp5i8/grib2io/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2oyh4krp
         cwd: /tmp/pip-install-a9lbp5i8/grib2io/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a9lbp5i8/grib2io/setup.py", line 184, in <module>
        libpath = os.path.dirname(os.path.realpath(find_library(lib)))
      File "/usr/lib64/python3.9/posixpath.py", line 390, in realpath
        filename = os.fspath(filename)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    Reading from setup.cfg...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 
```

The problem occures when  `_find_library_linux()` returns None. In my case it was because `openjp2` wasn't found in `libs`.

os.path.realpath() expects a str or path, and cannot handle None as an input.

At first glance it looks like a possible fix would be to replace line 184 in setup.py with something like:

```python
lib_path = find_library(lib)
if lib_path isinstance(lib_path, str):
    lib_dir_path = os.path.dirname(os.path.realpath(lib_path))
else:
    continue
```

**Comment by jasonwashburn** [comment]
I'll see if I can get a PR up for it today.

**Comment by jasonwashburn** [comment]
Submitted PR #21
